version: '2'

services:
    workspace:
      build: "./php53-apache"
      ports:
        - "${APACHE_PORT}:${APACHE_PORT}"
      # volumes でマウントの指定.こちらも相対パス.
      volumes:
        - ./workspace:/var/www/html
        - ./php53-apache/httpd.conf:/etc/httpd/conf/httpd.conf
        - ./logs/symfony/:/var/log/httpd/
      links:
        - postgres:postgres

    postgres:
      restart: always
      image: postgres:9.6.12-alpine
      environment:
        LC_ALL: C.UTF-8
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
        - ./pgsql-data:/var/lib/postgresql/data
      ports:
        - "${DB_PORT}:${DB_PORT}"
