indexSuccess:
  stylesheets: [brochure/index.css,common/reset.css]
  javascripts: [vendor/jquery/jquery-3.3.1.min.js, brochure/index.js]

roomSuccess:
  stylesheets: [brochure/index.css,common/reset.css]
  javascripts: [vendor/jquery/jquery-3.3.1.min.js, brochure/index.js]

seatSuccess:
  stylesheets: [brochure/index.css,common/reset.css]
  javascripts: [vendor/jquery/jquery-3.3.1.min.js, brochure/index.js]
