# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: playground, action: Index }

# generic rules
# please, remove them by adding more specific rules

room_list:
  url:  /room
  param:  { module: playground, action: Room }

seat:
  url:  /seat
  param:  { module: playground, action: Seat }

menu_list:
  url:  /menu_list
  param:  { module: playground, action: Seat }

notice:
  url:  /notice
  param:  { module: playground, action: Notice }

contact:
  url:  /contact
  param:  { module: playground, action: Contact }

default:
  url:   /:module/:action/*
